name: docker & react app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out
        uses: actions/checkout@v4

      - name: login to docker hub
        uses:  docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: addyjaime/app:latest